// @flow
export const LOGIN_TYPE = {
  PENDING: 'LOGIN_USER_PENDING',
  ERROR: 'LOGIN_USER_ERROR',
  SUCCESS: 'LOGIN_USER_SUCCESS',
  LOAD_LOCAL_DATA: 'LOAD_LOCAL_DATA',
  SIGN_OUT: 'SIGN_OUT',
  CLEAR: 'LOGIN_CLEAR',
  TWO_FACTOR: 'TWO_FACTOR_VERIFY',
  CACHED_DATA: 'LOAD_LOGIN_CACHED_DATA',
};

export const ACCOUNTS_TYPE = {
  SET_DATES: 'SET_DATES',
  SET_SELECTION: 'SET_SELECTION',
  REFRESH_DATA: 'REFRESH_DATA',
  CACHED_DATA: 'LOAD_ACCOUNTS_CACHED_DATA',
  ACCOUNTS: {
    PENDING: 'GET_ACCOUNTS_PENDING',
    SUCCESS: 'GET_ACCOUNTS_SUCCESS',
    ERROR: 'GET_ACCOUNTS_ERROR',
  },
  ASSETS: {
    PENDING: 'GET_ACCOUNT_ASSETS_PENDING',
    SUCCESS: 'GET_ACCOUNT_ASSETS_SUCCESS',
    ERROR: 'GET_ACCOUNT_ASSETS_ERROR',
  },
  CURRENCIES: {
    PENDING: 'GET_ACCOUNT_CURRENCIES_PENDING',
    SUCCESS: 'GET_ACCOUNT_CURRENCIES_SUCCESS',
    ERROR: 'GET_ACCOUNT_CURRENCIES_ERROR',
  },
};

export const INDICATORS_TYPE = {
  PENDING: 'GET_INDICATORS_PENDING',
  ERROR: 'GET_INDICATORS_ERROR',
  SUCCESS: 'GET_INDICATORS_SUCCESS',
};

export const LOOKUPS_TYPE = {
  PENDING: 'LOOKUPS_TYPE_PENDING',
  ERROR: 'LOOKUPS_TYPE_ERROR',
  SUCCESS: 'LOOKUPS_TYPE_SUCCESS',
};

export const SUMMARY_TYPE = {
  PENDING: 'GET_SUMMARY_PENDING',
  ERROR: 'GET_SUMMARY_ERROR',
  SUCCESS: 'GET_SUMMARY_SUCCESS',
};

export const CHANGE_PASSWORD_TYPE = {
  RESET: 'CHANGE_PASSWORD',
  PENDING: 'CHANGE_PASSWORD_PENDING',
  SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  ERROR: 'CHANGE_PASSWORD_ERROR',
  TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  TOKEN_ERROR: 'TOKEN_ERROR',
  CLEAR: 'PASSWORD_CLEAR',
};

export const REQUEST_PASSWORD_TYPE = {
  PENDING: 'REQUEST_PASSWORD_PENDING',
  SUCCESS: 'REQUEST_PASSWORD_SUCCESS',
  ERROR: 'REQUEST_PASSWORD_ERROR',
};

export const TRANSACTIONS = {
  INDICATORS: {
    PENDING: 'TRANSACTIONS_INDICATORS_PENDING',
    SUCCESS: 'TRANSACTIONS_INDICATORS_SUCCESS',
    ERROR: 'TRANSACTIONS_INDICATORS_ERROR',
  },
  ALL: {
    PENDING: 'TRANSACTIONS_ALL_PENDING',
    SUCCESS: 'TRANSACTIONS_ALL_SUCCESS',
    ERROR: 'TRANSACTIONS_ALL_ERROR',
  },
  SINGLE: {
    PENDING: 'TRANSACTIONS_SINGLE_PENDING',
    SUCCESS: 'TRANSACTIONS_SINGLE_SUCCESS',
    ERROR: 'TRANSACTIONS_SINGLE_ERROR',
  },
  BATCH: {
    PENDING: 'TRANSACTIONS_BATCH_PENDING',
    SUCCESS: 'TRANSACTIONS_BATCH_SUCCESS',
    ERROR: 'TRANSACTIONS_BATCH_ERROR',
    CLEAR: 'TRANSACTIONS_BATCH_CLEAR',
  },
  LOGS: {
    PENDING: 'TRANSACTIONS_LOGS_PENDING',
    SUCCESS: 'TRANSACTIONS_LOGS_SUCCESS',
    ERROR: 'TRANSACTIONS_LOGS_ERROR',
  },
  OPTIONS: {
    SUCCESS: 'TRANSACTIONS_SET_OPTIONS_SUCCESS',
  },
  RESPONSECODES: {
    PENDING: 'TRANSACTIONS_RESPONSECODES_PENDING',
    SUCCESS: 'TRANSACTIONS_RESPONSECODES_SUCCESS',
    ERROR: 'TRANSACTIONS_RESPONSECODES_ERROR',
  },
  SET_TRANSACTION_ACTION: 'SET_TRANSACTION_ACTION',
};

export const TRANSACTION_BLACKLIST = {
  PENDING: 'TRANSACTION_BLACKLIST_PENDING',
  SUCCESS: 'TRANSACTION_BLACKLIST_SUCCESS',
  ERROR: 'TRANSACTION_BLACKLIST_ERROR',
};

export const TRANSACTION_ACTIONS = {
  VOID: {
    PENDING: 'TRANSACTION_ACTION_VOID_PENDING',
    SUCCESS: 'TRANSACTION_ACTION_VOID_SUCCESS',
    ERROR: 'TRANSACTION_ACTION_VOID_ERROR',
  },
  VOID_BATCH: {
    PENDING: 'VOID_BATCH_PENDING',
    SUCCESS: 'VOID_BATCH_SUCCESS',
    ERROR: 'VOID_BATCH_ERROR',
  },
  REFUND: {
    PENDING: 'TRANSACTION_ACTION_REFUND_PENDING',
    SUCCESS: 'TRANSACTION_ACTION_REFUND_SUCCESS',
    ERROR: 'TRANSACTION_ACTION_REFUND_ERROR',
  },
  REFUND_BATCH: {
    PENDING: 'REFUND_BATCH_PENDING',
    SUCCESS: 'REFUND_BATCH_SUCCESS',
    ERROR: 'REFUND_BATCH_ERROR',
  },
  CAPTURE: {
    PENDING: 'TRANSACTION_ACTION_CAPTURE_PENDING',
    SUCCESS: 'TRANSACTION_ACTION_CAPTURE_SUCCESS',
    ERROR: 'TRANSACTION_ACTION_CAPTURE_ERROR',
  },
  CAPTURE_BATCH: {
    PENDING: 'CAPTURE_BATCH_PENDING',
    SUCCESS: 'CAPTURE_BATCH_SUCCESS',
    ERROR: 'CAPTURE_BATCH_ERROR',
  },
  BLACKLIST: {
    PENDING: 'TRANSACTION_ACTION_BLACKLIST_PENDING',
    SUCCESS: 'TRANSACTION_ACTION_BLACKLIST_SUCCESS',
    ERROR: 'TRANSACTION_ACTION_BLACKLIST_ERROR',
  },
};

export const CHARGES = {
  CREATE: {
    PENDING: 'CHARGES_CREATE_PENDING',
    SUCCESS: 'CHARGES_CREATE_SUCCESS',
    ERROR: 'CHARGES_CREATE_ERROR',
  },
  CLEAR: 'CHARGES_CLEAR',
};

export const PAYMENT_TYPE = {
  ALL: {
    PENDING: 'PAYMENT_TYPE_ALL_PENDING',
    SUCCESS: 'PAYMENT_TYPE_ALL_SUCCESS',
    ERROR: 'PAYMENT_TYPE_ALL_ERROR',
  },
  OPTIONS: {
    PENDING: 'PAYMENT_TYPE_OPTIONS_PENDING',
    SUCCESS: 'PAYMENT_TYPE_OPTIONS_SUCCESS',
    ERROR: 'PAYMENT_TYPE_OPTIONS_ERROR',
  },
};

export const BANNER_TYPE = {
  ALERT: {
    SHOW: 'ALERT_SHOW',
    HIDE: 'ALERT_HIDE',
  },
  NOTIFICATION: {
    SHOW: 'NOTIFICATION_SHOW',
    HIDE: 'NOTIFICATION_HIDE',
  },
};

export const CUSTOMERS = {
  INDICATORS: {
    PENDING: 'CUSTOMERS_INDICATORS_PENDING',
    SUCCESS: 'CUSTOMERS_INDICATORS_SUCCESS',
    ERROR: 'CUSTOMERS_INDICATORS_ERROR',
  },
  ALL: {
    PENDING: 'CUSTOMERS_ALL_PENDING',
    SUCCESS: 'CUSTOMERS_ALL_SUCCESS',
    ERROR: 'CUSTOMERS_ALL_ERROR',
  },
  SINGLE: {
    PENDING: 'CUSTOMERS_SINGLE_PENDING',
    SUCCESS: 'CUSTOMERS_SINGLE_SUCCESS',
    ERROR: 'CUSTOMERS_SINGLE_ERROR',
  },
  TRANSACTIONS: {
    PENDING: 'CUSTOMERS_TRANSACTIONS_PENDING',
    SUCCESS: 'CUSTOMERS_TRANSACTIONS_SUCCESS',
    ERROR: 'CUSTOMERS_TRANSACTIONS_ERROR',
    RESET: 'CUSTOMERS_TRANSACTIONS_RESET',
  },
  CARD_DEFAULT: {
    PENDING: 'CUSTOMERS_CARD_DEFAULT_PENDING',
    SUCCESS: 'CUSTOMERS_CARD_DEFAULT_SUCCESS',
    ERROR: 'CUSTOMERS_CARD_DEFAULT_ERROR',
  },
  CARD_UPDATE: {
    PENDING: 'CUSTOMERS_CARD_UPDATE_PENDING',
    SUCCESS: 'CUSTOMERS_CARD_UPDATE_SUCCESS',
    ERROR: 'CUSTOMERS_CARD_UPDATE_ERROR',
  },
  CARD_DELETE: {
    PENDING: 'CUSTOMERS_CARD_DELETE_PENDING',
    SUCCESS: 'CUSTOMERS_CARD_DELETE_SUCCESS',
    ERROR: 'CUSTOMERS_CARD_DELETE_ERROR',
  },
  PAYMENT_PLANS: {
    PENDING: 'CUSTOMERS_PAYMENT_PLANS_PENDING',
    SUCCESS: 'CUSTOMERS_PAYMENT_PLANS_SUCCESS',
    ERROR: 'CUSTOMERS_PAYMENT_PLANS_ERROR',
  },
  PAYMENT_PLANS_ACTIONS: {
    CHANGE_STATUS: {
      PENDING: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_CHANGE_STATUS_PENDING',
      SUCCESS: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_CHANGE_STATUS_SUCCESS',
      ERROR: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_CHANGE_STATUS_ERROR',
    },
    DELETE: {
      PENDING: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_DELETE_PENDING',
      SUCCESS: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_DELETE_SUCCESS',
      ERROR: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_DELETE_ERROR',
    },
    EDIT: {
      PENDING: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_EDIT_PENDING',
      SUCCESS: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_EDIT_SUCCESS',
      ERROR: 'CUSTOMERS_PAYMENT_PLANS_ACTIONS_EDIT_ERROR',
    },
  },
};

export const STATEMENTS = {
  PENDING: 'STATEMENTS_ALL_PENDING',
  SUCCESS: 'STATEMENTS_ALL_SUCCESS',
  ERROR: 'STATEMENTS_ALL_ERROR',
  STREAM_MONTH_SECTION_MAP: 'STATEMENTS_STREAM_MONTH_SECTION_MAP',
  GROUP: {
    PENDING: 'STATEMENTS_GROUP_PENDING',
    SUCCESS: 'STATEMENTS_GROUP_SUCCESS',
    ERROR: 'STATEMENTS_GROUP_ERROR',
  },
};

export const CUSTOMERS_ACTIONS = {
  UPDATE_DETAILS: {
    PENDING: 'CUSTOMERS_ACTIONS_UPDATE_DETAILS_PENDING',
    SUCCESS: 'CUSTOMERS_ACTIONS_UPDATE_DETAILS_SUCCESS',
    ERROR: 'CUSTOMERS_ACTIONS_UPDATE_DETAILS_ERROR',
  },
  CREATE_PAYMENT: {
    PENDING: 'CUSTOMERS_ACTIONS_CREATE_PAYMENT_PENDING',
    SUCCESS: 'CUSTOMERS_ACTIONS_CREATE_PAYMENT_SUCCESS',
    ERROR: 'CUSTOMERS_ACTIONS_CREATE_PAYMENT_ERROR',
    CLEAR: 'CUSTOMERS_ACTIONS_CREATE_PAYMENT_CLEAR',
  },
  ADD_CREDIT_CARD: {
    PENDING: 'CUSTOMERS_ACTIONS_ADD_CREDIT_CARD_PENDING',
    SUCCESS: 'CUSTOMERS_ACTIONS_ADD_CREDIT_CARD_SUCCESS',
    ERROR: 'CUSTOMERS_ACTIONS_ADD_CREDIT_CARD_ERROR',
  },
  ADD_PAYMENT_PLAN: {
    PENDING: 'CUSTOMERS_ACTIONS_ADD_PAYMENT_PLAN_PENDING',
    SUCCESS: 'CUSTOMERS_ACTIONS_ADD_PAYMENT_PLAN_SUCCESS',
    ERROR: 'CUSTOMERS_ACTIONS_ADD_PAYMENT_PLAN_ERROR',
  },
};

export const RISK_BLACKLIST = {
  ATTRIBUTES: {
    PENDING: 'RISK_BLACKLIST_ATTRIBUTES_PENDING',
    SUCCESS: 'RISK_BLACKLIST_ATTRIBUTES_SUCCESS',
    ERROR: 'RISK_BLACKLIST_ATTRIBUTES_ERROR',
  },
  ALL: {
    PENDING: 'RISK_BLACKLIST_ALL_PENDING',
    SUCCESS: 'RISK_BLACKLIST_ALL_SUCCESS',
    ERROR: 'RISK_BLACKLIST_ALL_ERROR',
  },
  DELETE: {
    PENDING: 'RISK_BLACKLIST_DELETE_PENDING',
    SUCCESS: 'RISK_BLACKLIST_DELETE_SUCCESS',
    ERROR: 'RISK_BLACKLIST_DELETE_ERROR',
  },
  ADD: {
    PENDING: 'RISK_BLACKLIST_ADD_PENDING',
    SUCCESS: 'RISK_BLACKLIST_ADD_SUCCESS',
    ERROR: 'RISK_BLACKLIST_ADD_ERROR',
  },
};

export const RISK_AVS = {
  ALL: {
    PENDING: 'RISK_AVS_ALL_PENDING',
    SUCCESS: 'RISK_AVS_ALL_SUCCESS',
    ERROR: 'RISK_AVS_ALL_ERROR',
  },
  LIST_ACTIONS: {
    PENDING: 'RISK_AVS_LIST_ACTIONS_PENDING',
    SUCCESS: 'RISK_AVS_LIST_ACTIONS_SUCCESS',
    ERROR: 'RISK_AVS_LIST_ACTIONS_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_AVS_SAVE_PENDING',
    SUCCESS: 'RISK_AVS_SAVE_SUCCESS',
    ERROR: 'RISK_AVS_SAVE_ERROR',
  },
};

export const RISK_VELOCITY = {
  ALL: {
    PENDING: 'RISK_VELOCITY_ALL_PENDING',
    SUCCESS: 'RISK_VELOCITY_ALL_SUCCESS',
    ERROR: 'RISK_VELOCITY_ALL_ERROR',
  },
  LIST_ACTIONS: {
    PENDING: 'RISK_VELOCITY_LIST_ACTIONS_PENDING',
    SUCCESS: 'RISK_VELOCITY_LIST_ACTIONS_SUCCESS',
    ERROR: 'RISK_VELOCITY_LIST_ACTIONS_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_VELOCITY_SAVE_PENDING',
    SUCCESS: 'RISK_VELOCITY_SAVE_SUCCESS',
    ERROR: 'RISK_VELOCITY_SAVE_ERROR',
  },
};

export const RISK_MISMATCH = {
  ALL: {
    PENDING: 'RISK_MISMATCH_ALL_PENDING',
    SUCCESS: 'RISK_MISMATCH_ALL_SUCCESS',
    ERROR: 'RISK_MISMATCH_ALL_ERROR',
  },
  LIST_ACTIONS: {
    PENDING: 'RISK_MISMATCH_LIST_ACTIONS_PENDING',
    SUCCESS: 'RISK_MISMATCH_LIST_ACTIONS_SUCCESS',
    ERROR: 'RISK_MISMATCH_LIST_ACTIONS_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_MISMATCH_SAVE_PENDING',
    SUCCESS: 'RISK_MISMATCH_SAVE_SUCCESS',
    ERROR: 'RISK_MISMATCH_SAVE_ERROR',
  },
};

export const RISK_THRESHOLD = {
  ALL: {
    PENDING: 'RISK_THRESHOLD_ALL_PENDING',
    SUCCESS: 'RISK_THRESHOLD_ALL_SUCCESS',
    ERROR: 'RISK_THRESHOLD_ALL_ERROR',
  },
  LIST_ACTIONS: {
    PENDING: 'RISK_THRESHOLD_LIST_ACTIONS_PENDING',
    SUCCESS: 'RISK_THRESHOLD_LIST_ACTIONS_SUCCESS',
    ERROR: 'RISK_THRESHOLD_LIST_ACTIONS_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_THRESHOLD_SAVE_PENDING',
    SUCCESS: 'RISK_THRESHOLD_SAVE_SUCCESS',
    ERROR: 'RISK_THRESHOLD_SAVE_ERROR',
  },
};

export const RISK_VERIFIED_INFO = {
  ALL: {
    PENDING: 'RISK_VERIFIED_INFO_ALL_PENDING',
    SUCCESS: 'RISK_VERIFIED_INFO_ALL_SUCCESS',
    ERROR: 'RISK_VERIFIED_INFO_ALL_ERROR',
  },
  LIST_ACTIONS: {
    PENDING: 'RISK_VERIFIED_INFO_LIST_ACTIONS_PENDING',
    SUCCESS: 'RISK_VERIFIED_INFO_LIST_ACTIONS_SUCCESS',
    ERROR: 'RISK_VERIFIED_INFO_LIST_ACTIONS_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_VERIFIED_INFO_SAVE_PENDING',
    SUCCESS: 'RISK_VERIFIED_INFO_SAVE_SUCCESS',
    ERROR: 'RISK_VERIFIED_INFO_SAVE_ERROR',
  },
};

export const RISK_COUNTRY = {
  ALL: {
    PENDING: 'RISK_COUNTRY_ALL_PENDING',
    SUCCESS: 'RISK_COUNTRY_ALL_SUCCESS',
    ERROR: 'RISK_COUNTRY_ALL_ERROR',
  },
  SAVE: {
    PENDING: 'RISK_COUNTRY_SAVE_PENDING',
    SUCCESS: 'RISK_COUNTRY_SAVE_SUCCESS',
    ERROR: 'RISK_COUNTRY_SAVE_ERROR',
  },
};

export const REPORTS = {
  ALL: {
    PENDING: 'REPORTS_ALL_PENDING',
    SUCCESS: 'REPORTS_ALL_SUCCESS',
    ERROR: 'REPORTS_ALL_ERROR',
  },
  GENERATE: {
    PENDING: 'REPORTS_GENERATE_PENDING',
    SUCCESS: 'REPORTS_GENERATE_SUCCESS',
    ERROR: 'REPORTS_GENERATE_ERROR',
  },
};

// SETTINGS
export const ACCOUNT_DETAILS = {
  PENDING: 'ACCOUNT_DETAILS_ALL_PENDING',
  SUCCESS: 'ACCOUNT_DETAILS_ALL_SUCCESS',
  ERROR: 'ACCOUNT_DETAILS_ALL_ERROR',
};

export const BANK_ACCOUNTS = {
  LIST: {
    PENDING: 'BANK_ACCOUNTS_LIST_PENDING',
    SUCCESS: 'BANK_ACCOUNTS_LIST_SUCCESS',
    ERROR: 'BANK_ACCOUNTS_LIST_ERROR',
  },
  UPDATE: {
    PENDING: 'BANK_ACCOUNTS_UPDATE_PENDING',
    SUCCESS: 'BANK_ACCOUNTS_UPDATE_SUCCESS',
    ERROR: 'BANK_ACCOUNTS_UPDATE_ERROR',
  },
  DETAILS: {
    PENDING: 'BANK_ACCOUNT_DETAILS_PENDING',
    SUCCESS: 'BANK_ACCOUNT_DETAILS_SUCCESS',
    ERROR: 'BANK_ACCOUNT_DETAILS_ERROR',
  },
  FIELDS: {
    PENDING: 'BANK_ACCOUNT_FIELDS_PENDING',
    SUCCESS: 'BANK_ACCOUNT_FIELDS_SUCCESS',
    ERROR: 'BANK_ACCOUNT_FIELDS_ERROR',
  },
};

export const ACCOUNT_SETTINGS = {
  PENDING: 'ACCOUNT_SETTINGS_ALL_PENDING',
  SUCCESS: 'ACCOUNT_SETTINGS_ALL_SUCCESS',
  ERROR: 'ACCOUNT_SETTINGS_ALL_ERROR',
};

export const PROCESSING_CURRENCIES = {
  PENDING: 'PROCESSING_CURRENCIES_ALL_PENDING',
  SUCCESS: 'PROCESSING_CURRENCIES_ALL_SUCCESS',
  ERROR: 'PROCESSING_CURRENCIES_ALL_ERROR',
};

export const APPLE_PAY = {
  SIGNING_REQUEST: {
    PENDING: 'APPLE_PAY_SIGNING_REQUEST_PENDING',
    SUCCESS: 'APPLE_PAY_SIGNING_REQUEST_SUCCESS',
    ERROR: 'APPLE_PAY_SIGNING_REQUEST_ERROR',
  },
  CERTIFICATES: {
    PENDING: 'APPLE_PAY_CERTIFICATES_PENDING',
    SUCCESS: 'APPLE_PAY_CERTIFICATES_SUCCESS',
    ERROR: 'APPLE_PAY_CERTIFICATES_ERROR',
  },
};

export const PROCESSING_SETTINGS = {
  PENDING: 'PROCESSING_SETTINGS_PENDING',
  SUCCESS: 'PROCESSING_SETTINGS_SUCCESS',
  ERROR: 'PROCESSING_SETTINGS_ERROR',
};

export const PAYMENT_METHODS = {
  PENDING: 'PAYMENT_METHODS_ALL_PENDING',
  SUCCESS: 'PAYMENT_METHODS_ALL_SUCCESS',
  ERROR: 'PAYMENT_METHODS_ALL_ERROR',
};

export const SERVICE_SETTINGS = {
  PENDING: 'SERVICE_SETTINGS_PENDING',
  SUCCESS: 'SERVICE_SETTINGS_SUCCESS',
  ERROR: 'SERVICE_SETTINGS_ERROR',
};

export const DISPLAY_CURRENCY = {
  UPDATE: {
    PENDING: 'DISPLAY_CURRENCY_UPDATE_PENDING',
    SUCCESS: 'DISPLAY_CURRENCY_UPDATE_SUCCESS',
    ERROR: 'DISPLAY_CURRENCY_UPDATE_ERROR',
  },
};

export const COUNTRY_CITIES = {
  PENDING: 'COUNTRY_CITIES_PENDING',
  SUCCESS: 'COUNTRY_CITIES_SUCCESS',
  ERROR: 'COUNTRY_CITIES_ERROR',
};

export const COUNTRY_TIMEZONES = {
  PENDING: 'COUNTRY_TIMEZONES_PENDING',
  SUCCESS: 'COUNTRY_TIMEZONES_SUCCESS',
  ERROR: 'COUNTRY_TIMEZONES_ERROR',
};

// USER MANAGEMENT
export const USER_MANAGEMENT = {
  LIST_USERS: {
    PENDING: 'USER_MANAGEMENT_LIST_USERS_PENDING',
    SUCCESS: 'USER_MANAGEMENT_LIST_USERS_SUCCESS',
    ERROR: 'USER_MANAGEMENT_LIST_USERS_ERROR',
  },
  CREATE_USER: {
    PENDING: 'USER_MANAGEMENT_CREATE_USER_PENDING',
    SUCCESS: 'USER_MANAGEMENT_CREATE_USER_SUCCESS',
    ERROR: 'USER_MANAGEMENT_CREATE_USER_ERROR',
  },
  UPDATE_USER: {
    PENDING: 'USER_MANAGEMENT_UPDATE_USER_PENDING',
    SUCCESS: 'USER_MANAGEMENT_UPDATE_USER_SUCCESS',
    ERROR: 'USER_MANAGEMENT_UPDATE_USER_ERROR',
  },
  DELETE_USER: {
    PENDING: 'USER_MANAGEMENT_DELETE_USER_PENDING',
    SUCCESS: 'USER_MANAGEMENT_DELETE_USER_SUCCESS',
    ERROR: 'USER_MANAGEMENT_DELETE_USER_ERROR',
  },
};

// PAYMENT PLANS
export const PAYMENT_PLAN = {
  ALL: {
    PENDING: 'PAYMENT_PLAN_ALL_PENDING',
    SUCCESS: 'PAYMENT_PLAN_ALL_SUCCESS',
    ERROR: 'PAYMENT_PLAN_ALL_ERROR',
  },
  UPDATE: {
    PENDING: 'PAYMENT_PLAN_UPDATE_PENDING',
    SUCCESS: 'PAYMENT_PLAN_UPDATE_SUCCESS',
    ERROR: 'PAYMENT_PLAN_UPDATE_ERROR',
  },
};

// PROFILE
export const PROFILE_UPDATE = {
  PENDING: 'PROFILE_UPDATE_PENDING',
  SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  ERROR: 'PROFILE_UPDATE_ERROR',
};

// FREQUENCIES
export const FREQUENCIES = {
  PENDING: 'FREQUENCIES_PENDING',
  SUCCESS: 'FREQUENCIES_SUCCESS',
  ERROR: 'FREQUENCIES_ERROR',
};

export const API_KEYS = {
  PENDING: 'API_KEYS_PENDING',
  SUCCESS: 'API_KEYS_SUCCESS',
  ERROR: 'API_KEYS_ERROR',
};

export const APP_TYPE = {
  SET_TITLE: 'SET_TITLE',
  SET_ACTIVE_ROW: 'SET_ACTIVE_ROW',
  PUSH_ROW_DETAILS_STACK: 'PUSH_ROW_DETAILS_STACK',
  CLEAR_ROW_DETAILS_STACK: 'CLEAR_ROW_DETAILS_STACK',
  SLICE_ROW_DETAILS: 'SLICE_ROW_DETAILS',
  COLLAPSE_SIDEBAR: 'COLLAPSE_SIDEBAR',
};

export const TABLE_TYPE = {
  SELECTED_ROWS: 'TABLE_SELECTED_ROWS',
  SEARCH: 'TABLE_SEARCH',
  SORT: 'TABLE_SORT',
  PAGINATION: 'TABLE_PAGINATION',
  FILTER: 'TABLE_FILTER',
  CLEAR_FILTER: 'TABLE_CLEAR_FILTER',
  RESET_OPTIONS: 'RESET_OPTIONS',
  RESET_FILTER: 'RESET_FILTER',
  RESET_SELECTION: 'RESET_SELECTION',
  RESET: 'TABLE_RESET',
};
