// flow-typed signature: d00f0df3b801622d2167878240bd1799
// flow-typed version: <<STUB>>/cucumber-html-reporter_v^3.0.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cucumber-html-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cucumber-html-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cucumber-html-reporter/lib/hierarchyReporter' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/lib/jsonDir' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/lib/searchFileUp' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/piechart' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/script' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/templates/_common/foundation/script' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/templates/_common/screenshot' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/templates/simple/script' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/test/assert/assertHtmlReports' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/test/createHtmlReports' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/test/features/step_definitions/hooks' {
  declare module.exports: any;
}

declare module 'cucumber-html-reporter/test/features/step_definitions/stepDefs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cucumber-html-reporter/index' {
  declare module.exports: $Exports<'cucumber-html-reporter'>;
}
declare module 'cucumber-html-reporter/index.js' {
  declare module.exports: $Exports<'cucumber-html-reporter'>;
}
declare module 'cucumber-html-reporter/lib/hierarchyReporter.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/lib/hierarchyReporter'>;
}
declare module 'cucumber-html-reporter/lib/jsonDir.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/lib/jsonDir'>;
}
declare module 'cucumber-html-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/lib/reporter'>;
}
declare module 'cucumber-html-reporter/lib/searchFileUp.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/lib/searchFileUp'>;
}
declare module 'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/piechart.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/piechart'>;
}
declare module 'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/script.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/templates/_common/bootstrap.hierarchy/script'>;
}
declare module 'cucumber-html-reporter/templates/_common/foundation/script.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/templates/_common/foundation/script'>;
}
declare module 'cucumber-html-reporter/templates/_common/screenshot.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/templates/_common/screenshot'>;
}
declare module 'cucumber-html-reporter/templates/simple/script.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/templates/simple/script'>;
}
declare module 'cucumber-html-reporter/test/assert/assertHtmlReports.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/test/assert/assertHtmlReports'>;
}
declare module 'cucumber-html-reporter/test/createHtmlReports.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/test/createHtmlReports'>;
}
declare module 'cucumber-html-reporter/test/features/step_definitions/hooks.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/test/features/step_definitions/hooks'>;
}
declare module 'cucumber-html-reporter/test/features/step_definitions/stepDefs.js' {
  declare module.exports: $Exports<'cucumber-html-reporter/test/features/step_definitions/stepDefs'>;
}
