// flow-typed signature: 0fca5da7cb4f0b952b6426dbc69348b9
// flow-typed version: <<STUB>>/gulp-release-it_v^1.1.14/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-release-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-release-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-release-it/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-release-it/main' {
  declare module.exports: any;
}

declare module 'gulp-release-it/tag_version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-release-it/gulpfile.js' {
  declare module.exports: $Exports<'gulp-release-it/gulpfile'>;
}
declare module 'gulp-release-it/main.js' {
  declare module.exports: $Exports<'gulp-release-it/main'>;
}
declare module 'gulp-release-it/tag_version.js' {
  declare module.exports: $Exports<'gulp-release-it/tag_version'>;
}
