// flow-typed signature: 6f79e7ef80f7f3c80a6872954a127fa0
// flow-typed version: <<STUB>>/notp_v^2.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notp/examples/TOTP-verify' {
  declare module.exports: any;
}

declare module 'notp/examples/TOTP' {
  declare module.exports: any;
}

declare module 'notp/test/notp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notp/examples/TOTP-verify.js' {
  declare module.exports: $Exports<'notp/examples/TOTP-verify'>;
}
declare module 'notp/examples/TOTP.js' {
  declare module.exports: $Exports<'notp/examples/TOTP'>;
}
declare module 'notp/index' {
  declare module.exports: $Exports<'notp'>;
}
declare module 'notp/index.js' {
  declare module.exports: $Exports<'notp'>;
}
declare module 'notp/test/notp.js' {
  declare module.exports: $Exports<'notp/test/notp'>;
}
