// flow-typed signature: 70a8d8eda8c7326d37266b5b3cb00b0f
// flow-typed version: <<STUB>>/thirty-two_v^1.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thirty-two'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thirty-two' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thirty-two/lib/thirty-two/index' {
  declare module.exports: any;
}

declare module 'thirty-two/lib/thirty-two/thirty-two' {
  declare module.exports: any;
}

declare module 'thirty-two/spec/thirty-two_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thirty-two/index' {
  declare module.exports: $Exports<'thirty-two'>;
}
declare module 'thirty-two/index.js' {
  declare module.exports: $Exports<'thirty-two'>;
}
declare module 'thirty-two/lib/thirty-two/index.js' {
  declare module.exports: $Exports<'thirty-two/lib/thirty-two/index'>;
}
declare module 'thirty-two/lib/thirty-two/thirty-two.js' {
  declare module.exports: $Exports<'thirty-two/lib/thirty-two/thirty-two'>;
}
declare module 'thirty-two/spec/thirty-two_spec.js' {
  declare module.exports: $Exports<'thirty-two/spec/thirty-two_spec'>;
}
